script:
  garagentor_impuls:
    alias: Garagentor Impuls
    sequence:
      - action: button.press
        target:
          entity_id: button.aussenbereich_garage_garagentor_impuls

template:
  - cover:
      - name: "Garagentor"
        unique_id: knx_garagentor_virtual_cover
        device_class: garage

        availability: >
          {{ states('binary_sensor.aussenbereich_garage_garagentor_status') in ['on', 'off'] }}

        state: >
          {% set door_state = states('binary_sensor.aussenbereich_garage_garagentor_status') %}
          {% if door_state == 'on' %}
            open
          {% else %}
            closed
          {% endif %}

        open_cover:
          - action: script.garagentor_impuls

        close_cover:
          - action: script.garagentor_impuls

        stop_cover:
          - action: script.garagentor_impuls

sensor:
  - platform: history_stats
    name: "Garage Garagentor Offen-Dauer Stunde"
    unique_id: garage_garagentor_offen_dauer_stunde
    entity_id: binary_sensor.aussenbereich_garage_garagentor_status
    state: "on"
    type: time
    start: "{{ (as_timestamp(now()) // 3600) * 3600 }}"
    end: "{{ now() }}"
    state_class: total_increasing
